stages:

  preprocessing:
    cmd: python src/data/make_dataset.py data/raw/train.csv data/interim/train_postproc.csv
    deps:
      - data/raw/train.csv
      - src/data/make_dataset.py
    outs:
      - data/interim/train_postproc.csv

  optimization:
    cmd: python src/models/train_model.py data/interim/train_postproc.csv models/model.clf
    deps:
      - data/interim/train_postproc.csv
      - src/models/train_model.py
    outs:
      - models/model.clf